<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Application\ProjectMetricsMonitor.Application.csproj" />
    <ProjectReference Include="..\Domain\ProjectMetricsMonitor.Domain.csproj" />
    <ProjectReference Include="..\Persistence\ProjectMetricsMonitor.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="7.6.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
